
# uiptool build configuration

image: nokturnaldock/uiptooldevenv:latest

clone:
  depth: full

pipelines:
  default:
    - step:
        name: 'Get libcmini, build and upload'
        deployment: production
        script:
          - export GIT_COMMIT=$(git log --pretty=format:'%h' -n 1)
          - mkdir ../libcmini
          - cd ../libcmini
            # Build breaks with libcmini >= 0.52!
          - wget -q -O - "https://github.com/freemint/libcmini/releases/download/v0.51/libcmini-0.51.tar.gz" | tar xzf -
          - export LIBCMINI="$PWD/lib/"
          - mkdir ../builddir
          - cd ../builddir
          - scons -C ${BITBUCKET_CLONE_DIR}
          - TARGETDIR=`basename ${BITBUCKET_CLONE_DIR}`
          - cp ./netusbee/${TARGETDIR}/src/*.tos ${BITBUCKET_CLONE_DIR} 
          - cp ./netusbee/${TARGETDIR}/src/uip.tos ./uip-netusbee-${BITBUCKET_BRANCH}.tos
          - cp ./usb/${TARGETDIR}/src/*.tos ${BITBUCKET_CLONE_DIR}
          - cp ./usb/${TARGETDIR}/src/uip.tos ./uip-usb-${BITBUCKET_BRANCH}.tos
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./uip-netusbee-${BITBUCKET_BRANCH}.tos"
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./uip-usb-${BITBUCKET_BRANCH}.tos"
        artifacts:
            # Save resulting files
          - uip-netusbee-${BITBUCKET_BRANCH}.tos
          - uip-usb-${BITBUCKET_BRANCH}.tos

