vpath %.html ../apps/atari/

index.h: webinterface.html
	$(CPP) -traditional-cpp -DVERSION=$(version) -P -o index.html $<
	gzip -9 -f index.html -c > index.html.gz
	xxd -i index.html.gz > $@
	sed -i -e 's/unsigned/static const unsigned/g' $@

icons: loader.h close.h

%.h: %.png
	xxd -i $< > $@

%.h: %.gif
	xxd -i $< > $@

.PHONY: staticdata
staticdata: index.h icons

*.c: staticdata

APP_SOURCES+=atarid.c
