Import('targetEnv')
Import('hostEnv')
import os.path

SOURCES = [
        "main.c",
        "uip_arch.c",
        "clock-arch.c",
        "ioredirect.c",
        "common.c",
        targetEnv.Vasm('ioredirect-trap.s'),
        Glob('uip/*.c'),
        Glob('uip/drivers/*.c'),
        targetEnv.SConscript("atari_ftp_server/SConscript", exports=['hostEnv', 'targetEnv']),
        targetEnv.SConscript("atari_http_server/SConscript", exports=['hostEnv', 'targetEnv'])
    ]

targetEnv.Append( CPPPATH=[ Dir('./uip').srcnode().abspath ] )
targetEnv.Append( CPPPATH=[ Dir('./').srcnode().abspath ] )

TARGETS =[
    targetEnv.Program("uip.tos", source = SOURCES),
    targetEnv.Program("romtest.tos", "romport-speed.c"),
    targetEnv.Program("contest.tos", "console-helper.c")
]

Return (["TARGETS"])